// <auto-generated />
using System;
using LoteriaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoteriaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421045551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Loteria.Core.Entities.Concurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acumulou")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSorteio")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalSorteio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipioUFSorteio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroConcurso")
                        .HasColumnType("int");

                    b.Property<string>("NumerosSorteados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premiacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoLoteriaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorAcumuladoProximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorArrecadado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoLoteriaId", "NumeroConcurso")
                        .IsUnique();

                    b.ToTable("Concursos");
                });

            modelBuilder.Entity("Loteria.Core.Entities.NumerosGerados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraGeracao")
                        .HasColumnType("time");

                    b.Property<string>("Numeros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoLoteriaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoLoteriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("NumerosGerados");
                });

            modelBuilder.Entity("Loteria.Core.Entities.TipoLoteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxNumero")
                        .HasColumnType("int");

                    b.Property<int>("MinNumero")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QuantidadeNumeros")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loterias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxNumero = 60,
                            MinNumero = 1,
                            Nome = "MEGA-SENA",
                            QuantidadeNumeros = 6
                        },
                        new
                        {
                            Id = 2,
                            MaxNumero = 25,
                            MinNumero = 1,
                            Nome = "LOTOFACIL",
                            QuantidadeNumeros = 15
                        });
                });

            modelBuilder.Entity("Loteria.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Loteria.Core.Entities.Concurso", b =>
                {
                    b.HasOne("Loteria.Core.Entities.TipoLoteria", "TipoLoteria")
                        .WithMany("Concursos")
                        .HasForeignKey("TipoLoteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoLoteria");
                });

            modelBuilder.Entity("Loteria.Core.Entities.NumerosGerados", b =>
                {
                    b.HasOne("Loteria.Core.Entities.TipoLoteria", "TipoLoteria")
                        .WithMany("NumerosGerados")
                        .HasForeignKey("TipoLoteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loteria.Core.Entities.Usuario", "Usuario")
                        .WithMany("NumerosGerados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoLoteria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Loteria.Core.Entities.TipoLoteria", b =>
                {
                    b.Navigation("Concursos");

                    b.Navigation("NumerosGerados");
                });

            modelBuilder.Entity("Loteria.Core.Entities.Usuario", b =>
                {
                    b.Navigation("NumerosGerados");
                });
#pragma warning restore 612, 618
        }
    }
}
